### ISSUE TITLE
The loss function in the implementation is different from that in the paper

### ISSUE THREAD

**Issue by WelkinYang** [sangyun884/fast-ode#1]
Thanks for your great work~ I found that the loss function in the implementation is different from that in the paper

Paper:
![image](https://user-images.githubusercontent.com/18493279/235051413-307dac81-addd-4489-9267-b332b8622f65.png)
Implemention:
target is not x but (x - z) and there is no the coefficient 1/(lambda)^2.
Hope to get a reply

**Comment by sangyun884** [comment]
Hi,

Please refer to Eqs 19, 20, and 21 in Appendix A.
